version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    volumes:
      - stationSki:/var/lib/mysql
    
  app-ski:
    image: khairidinne/gestionski:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root"
      }'
    ports:
      - "8089:8089"
    depends_on:
      - mysql

volumes:
  stationSki:
