version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3307:3306"  # Host uses 3307, internal stays 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  nexus:
    image: sonatype/nexus3
    container_name: nexus-server
    ports:
      - "8083:8081"  # Host 8083 -> Container 8081
      - "8084:8083"  # Optional second port
    volumes:
      - nexus-data:/nexus-data
    networks:
      - app-network
    restart: always

  spring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nihed/gestion-pist:latest
    container_name: spring-backend
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      # JPA Config
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"

      # Server Config
      SERVER_PORT: 8082
      TZ: Africa/Tunis

    ports:
      - "8082:8082"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/pistes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
  nexus-data:
  sonar_db_data:

networks:
  app-network:
