version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - stationSki:/var/lib/mysql
    networks:
      - springboot-network

  springboot-app:
    image: maramnaderi/my-app:latest
    container_name: springboot-container
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    networks:
      - springboot-network

volumes:
  stationSki:

networks:
  springboot-network:
