version: '3.8'

services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    volumes:
      - stationSki:/var/lib/mysql
    networks:
      - frontend_network

  app-ski:
    container_name: app-ski-backend
    depends_on:
      - mysql
    image: khairidinne/gestionski:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - frontend_network

volumes:
  stationSki:

networks:
  frontend_network:
    driver: bridge
