version: '3.8'

services:
  # Service pour la base de données MySQL
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    volumes:
      - stationSki:/var/lib/mysql

  # Service backend Spring Boot
  app-ski:
    depends_on:
      - mysql
    image: haythemraggad/my-app:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true



# Volumes pour persistance des données MySQL
volumes:
  stationSki:

# Networks pour isoler les services
networks:
  frontend_network:
    driver: bridge
