global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app-ski:8089']
        labels:
          instance: "app-ski"
    metrics_path: /actuator/prometheus
